### ISSUE TITLE
Can you please provide a released version / pre-version ?

### ISSUE THREAD

**Issue by ohault** [smx-smx/Winter#1]

**Comment by smx-smx** [comment]
I'll look into setting up CI for publishing artifacts.

I should also add a README to give some info/status on the project.
Lately there hasn't been much progress due to real life things, but I'd like to come back to this eventually.

By the way, don't expect too much in term of functionality as of now.
The idea would be to end up with a tool that can export and import packages from Windows installations, as well as listing information for each file in WinSxS.
What's implemented as of now is some rudimentary functionality to select a Windows installation and list packages.

The most similar tool would be https://github.com/seven-mile/UFCase

**Comment by smx-smx** [comment]
Done, binaries are now available from Cirrus CI.
Each build has a `binaries` section available with a .zip archive of the build

For example, here is the last build: https://cirrus-ci.com/task/4727774381867008

**Comment by ohault** [comment]
I have just tried this build on Windows 10 Pro 22H2 and it is not working. A window seems to open and close immediately.

**Comment by smx-smx** [comment]
Just to confirm, you ran `Smx.Winter.Gui.exe` as admin, right?
I'm also on Windows 10 22H2 and it works fine here

Edit: nvm I found an issue (but still, a window does open for me)

![Image](https://github.com/user-attachments/assets/1289f4c7-2b17-4f8b-a92e-1bf8ff3ccbaf)

**Comment by smx-smx** [comment]
It seems to be an issue with Cirrus CI, since I cannot reproduce it with a local build.
Looking into it

**Comment by smx-smx** [comment]
It should be fixed now, `wwwroot` was mistakenly excluded from git

Note: if you get an error on launch about Application Failed to initialize (0xc0000142), just try running again.
There's a sporadic error on startup that I need to debug

**Comment by ohault** [comment]
I have just checked with the latest build generated for b51222a commit and it is still not working. This time, I cannot event see a window trying to open on the screen.

**Comment by smx-smx** [comment]
Do you have the ASP.NET Runtime installed?
I tried on a clean Windows VM, and I could not get a window to appear either until I installed this:

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10

**Comment by ohault** [comment]
I can try, but for a desktop user, it is somehow weird to have to install ASP.NET. Isn't?

**Comment by ohault** [comment]
Thank you. To get it working, I had to install in the following order :

1) .NET 8.0 Desktop Runtime
2) ASP.NET Core Runtime 8.0

**Comment by smx-smx** [comment]
> I can try, but for a desktop user, it is somehow weird to have to install ASP.NET. Isn't?

The GUI is written in Blazor.NET, which is a web technology.
It can be used to write Desktop applications with the help of Photino.NET (https://www.tryphotino.io/)

If you right click anywhere in the web UI, you'll notice you can "Inspect" the page, because you're looking at an EdgeWebView2 instance, aka Chrome.

Thanks for confirming anyways, I'll list the requirements in the README.

**Comment by ohault** [comment]
Thank, there may already be a way to deploy the Blazor.NET desktop app along with all depencencies to have a better user experience. If it is not the case, it could be worth to file a feature request to Blazor.NET team about this.

**Comment by smx-smx** [comment]
It should be possible to build a self-contained app, though that will greatly increase the size of the build (to include all framework libraries).
I'm not sure it's worth doing at this stage

**Comment by ohault** [comment]
> It should be possible to build a self-contained app, though that will greatly increase the size of the build (to include all framework libraries).
> I'm not sure it's worth doing at this stage
> 

Required dependencies could perhaps also be downloaded and installed at first launch.
